- name: set the value of bridge iptable
  command: bash -c 'echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables'

- name: set the value of ipv4/ip_forward
  command: bash -c 'echo 1 > /proc/sys/net/ipv4/ip_forward'

# - name: net.bridge.bridge-nf-call-iptables settup
#   sysctl:
#     name: net.bridge.bridge-nf-call-iptables
#     value: 1
#     state: present
#     # 기본 PATH에 추가되어 있지 않아 절대 경로 설정

# - name: net.ipv4.ip_forward settup
#   sysctl:
#     name: net.ipv4.ip_forward
#     value: 1
#     state: present