# https://gist.github.com/yonglai/d4617d6914d5f4eb22e4e5a15c0e9a03
# docker 설치와 기본 설정
# ansible-playbook -i ./hosts.dev.yaml ./docker/docker.install.yaml --become --become-user=root
---
- hosts: docker
  tasks:
      - name: Install yum utils
        yum:
          name: yum-utils
          state: latest

      - name: Install device-mapper-persistent-data
        yum:
          name: device-mapper-persistent-data
          state: latest

      - name: Install lvm2
        yum:
          name: lvm2
          state: latest

      - name: Add Docker repo
        get_url:
          url: https://download.docker.com/linux/centos/docker-ce.repo
          dest: /etc/yum.repos.d/docer-ce.repo
        become: yes

      - name: Disable Docker Edge repo
        ini_file:
          dest: /etc/yum.repos.d/docer-ce.repo
          section: 'docker-ce-edge'
          option: disabled
          value: 0
        become: yes

      - name: Disable Docker Test repo
        ini_file:
          dest: /etc/yum.repos.d/docer-ce.repo
          section: 'docker-ce-test'
          option: disabled
          value: 0
        become: yes

      - name: Install Docker
        package:
          name: docker-ce
          state: latest
        become: yes

      - name: Add user root(irteamsu) to docker group
        user:
          name: irteamsu
          groups: docker
          append: yes
        become: yes

      - name: Creates docker directory for config
        file:
          path: /etc/docker
          state: directory
          owner: root
          group: docker
          mode: 0775

      - name: config daemon (docker directory path - /home is large allocated space)
        copy:
          src: ./docker-daemon.json # ncloud 서버의 디스크 파티션이 /home에 90% 가 할당되어 있음
          dest: "/etc/docker/daemon.json"
        register: daemon_result

      - name: Start Docker service
        service:
          name: docker
          state: started
          enabled: yes
        become: yes

      - name: Restart Docker service
        service:
          name: docker
          state: restarted
          enabled: yes
        when: daemon_result.changed == True
